# Generated by Django 2.1.3 on 2018-12-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
